### ISSUE TITLE
Remove thumbnail from calendar

### ISSUE THREAD

**Issue by msanco** [whroman/wolf_kino#4]
In the "Kalender" (deutsch) the days that only have one event display an image. However, the days with two events display only text. Ideally, no image should be displayed on the Kalendar.

**Comment by whroman** [comment]
This is a large task, it'll take some time.

**Comment by msanco** [comment]
Let's wait with this. Maybe it doesn't make sense to invest time into this if we are going to change the calendar in the near future.
