### ISSUE TITLE
wrong translation displayed on home page

### ISSUE THREAD

**Issue by msanco** [whroman/wolf_kino#5]
When on the homepage, the spotlight post for the DE page links to the EN blogpost (and not the DE one) and on the EN page it does the same (displays de EN blog post). 

DE should link to DE journal 
EN should link to EN journal

**Comment by whroman** [comment]
@msanco Do you know if this something that can be changed at the content entry level?

**Comment by msanco** [comment]
@whroman It was! Playing around a bit I found a way of doing it. You can close this issue.
