### ISSUE TITLE
Journal as a top level menu not displayed

### ISSUE THREAD

**Issue by msanco** [whroman/wolf_kino#6]
Even though I have enabled the top level menu 'Journal' it's not displayed on the menu bar.

**Comment by msanco** [comment]
Actually, I realised this is a problem for all pages we want to have on the menu bar e.g it would be good if 'tickets' were there as well (it's currently under Program).

**Comment by whroman** [comment]
@msanco Can you create a separate issue for the "tickets" thing? And describe it a bit more?

**Comment by whroman** [comment]
@msanco regarding the "Journal" issue, I'll take a look tonight

**Comment by whroman** [comment]
@msanco Can you describe the Journal page a bit? It looks like "Journal" should lead to a single, uninternationalized page. Is that right?

**Comment by msanco** [comment]
This issue has been solved. It can be closed.
