### ISSUE TITLE
'Ticket' top level menu not visible when enabled

### ISSUE THREAD

**Issue by msanco** [whroman/wolf_kino#7]
The tiket top level menu (which on squarespace is a "page") is enabled, both in German and English, but it's not visiable inte menu bar. The url slugs for these pages are
/en/tickets-1
/de/tickets-1

**Comment by whroman** [comment]
@msanco I've noticed that there's a new section under "What's on" called "Tickets" for both ENG and DEU, whose content is the same as the top-level "Tickets" page.

Does that mean that this issue has been resolved?

**Comment by whroman** [comment]
@msanco This is live now. I de-activated the "Tickets" pages that were under "Program". It looked like you were also trying to do this with the "Visit Us" page, so I deactivated the ones under "About". 

In other words, "Tickets" and "Visit Us" now appear as top-level navigation.
