### ISSUE TITLE
Clicking on top level menu get's you to the first page of 2nd level

### ISSUE THREAD

**Issue by msanco** [whroman/wolf_kino#8]
Basically, what you removed we should add again. So that when you click on "about" you get to "kino". So what happened was that we tested the webpage on some people and 9/10 people got confused by the fact that you could not click but only hover...

**Comment by whroman** [comment]
@msanco Yeah, I see what you/they mean, but I do think that the original nav menu was also confusing.

I applied some styling to the nav that, I hope, makes the menu easier for users to understand. Can you let me know what you think about these changes? They are live. The code is here: https://github.com/whroman/wolf_kino/commit/7d4edc187149202a196e47f98fcbec627b29e394
