### ISSUE TITLE
Embed FB feed

### ISSUE THREAD

**Issue by msanco** [whroman/wolf_kino#9]
Embed our facebook feed to pur homepage. Under "follow us" > instagram feed > facebook feed.
I found a way to generate a code in JavaScript but I'm to afraid to destroy any of the good job you've done so I'm just going to paste it here:

```
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.8";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>


<div class="fb-page" data-href="https://www.facebook.com/wolfkino/" data-tabs="timeline" data-width="500" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="false"><blockquote cite="https://www.facebook.com/wolfkino/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/wolfkino/">Wolf</a></blockquote></div>
```

**Comment by msanco** [comment]
Don't know why it doesn't let me to add the first code in that cool way but only the second one but I hope it's readable 😸

**Comment by whroman** [comment]
@msanco styling fixed :D ill get to this this weekend

**Comment by whroman** [comment]
resolved by https://github.com/whroman/wolf_kino/commit/6f49149e8283d0deec9080189fc8f4f72b7734a1
